---
title: "US irrigation"
author: "Dr. Chih-Yu Hung"
date: "2025-01-09"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
#Read 2017 and 2022 Census data

load("Inputs/US_census2017.RData")
load("Inputs/US_census2022.RData")

Croplist <-  c("BARLEY","CAMELINA","CANOLA","CORN",
               "PEAS","RYE","SORGHUM","SOYBEANS",
                "TRITICALE","WHEAT")
```

## The purpose of this MD is to calculate irrigation proportion (%) based on US census data. 

The irrigation data in the US census have two part, 1. total irrigated land in the states and 2. irrigated land for specific crops.

They have COUNTY LEVEL data for irrigated land, but many data are suppressed. Use total irrigated land area at State level. 

```{r select irrigation data}

US_irri_17 <- US_census2017 %>%
  filter(!(STATE_ALPHA %in% c("AK","GU","AS","PR","VI","MP","","HI",""))) %>% #exclude territories, HI and AK
  filter(COMMODITY_DESC %in% Croplist) %>% #interested crops
  filter(PRODN_PRACTICE_DESC == "IRRIGATED") %>%
  filter(UNIT_DESC == "ACRES") %>%
  filter(grepl("IRRIGATED - ACRES HARVESTED",SHORT_DESC,ignore.case =TRUE)) %>%
  filter(DOMAIN_DESC == "TOTAL") %>%
  filter(AGG_LEVEL_DESC == "STATE")
  
US_irri_22 <- US_census2022 %>%
  filter(!(STATE_ALPHA %in% c("AK","GU","AS","PR","VI","MP","","HI",""))) %>% #exclude territories, HI and AK
  filter(COMMODITY_DESC %in% Croplist) %>% #interested crops
  filter(PRODN_PRACTICE_DESC == "IRRIGATED") %>%
  filter(UNIT_DESC == "ACRES") %>%
  filter(grepl("IRRIGATED - ACRES HARVESTED",SHORT_DESC,ignore.case =TRUE)) %>%
  filter(DOMAIN_DESC == "TOTAL") %>%
  filter(AGG_LEVEL_DESC == "STATE")  
  
  

```
